sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: uF67aRNJoy5YyBwyJXowTOu6LTp4UwkgvNBXIXIHR92h6TdJJldWrQw4cwNdDSXbnWwA9gaBXWjM0+ccJGX1OeTGDX+OAfBBNkrGWl4bD0b6vHd1xJM5yWVYek+7AaQY+sf7gHaRT96iCsmV2L6jEUlNNiCnQgXdtyv3dyGzLqEktW+zDKWafZ4dGnJGi7MWb50HRMpL5XCLOiMEQi9X/YjwXtjOZGp+7hq+kt4JhS82syTPaO6mdGmh9k1xLEgDi0HTuhuk1MF7lAUTlLaRLUyr0G5JiKgVNVCy96+MHTRtLLSiFr3IoSrehy1Dv9ltKA5o6RQohvYk6hny25gH+aBWYMEqehB7CeVLNaYCNsKqXN+oURy3DoN0lMhKNbkxd7hWkHeBbiHVK66jyTKJTji97LFLC4xtR8N1ZdG9TzUR3WXC9yEcrCnlzw6mjeQQvCszPSMtHX5dtEM7vRx/Ixm/XA5cZ4XRsEagHciUlgLLgDtQPSj1ALfykySc60oLQBIFy+xHlReTSy+3iZ91JpZ68n3S+hEVz61ryEd0sppJSqbyNN/hTWeRXZYRbkwMv3uVOIyYI7Pj7k4OAcwwtObBrYTYkA8x1gmw6jXs/C+DzlhfT5kfLzVGi4tVAbcuAJT0ObwvgFgxOyjhVDDikJTBYaJFscFP6eqC7xUJblc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Canadian-Dominion--A-Chronicle-of-Our-Northern-Neighbor_2835
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy